### ISSUE TITLE
numpy failing to install: yum install python-bottle numpy -y' returned a non-zero code: 1

### ISSUE THREAD

**Issue by noahpresler** [knowledge-discovery/fall-2016#1]
Anybody run into this error? Would really appreciate
I am on Ubuntu 16.04 VM

![image](https://cloud.githubusercontent.com/assets/7767915/18332701/adaa2e2c-7536-11e6-917f-48d90e1025d4.png)

**Comment by TomLippincott** [comment]
I've seen this show up as an ephemeral error due to network timeouts: does it happen consistently, and on what network?

**Comment by noahpresler** [comment]
It seems to be a network issue like you said, I am working on setting up a bridged network rather than NAT. Hopefully this helps.

**Comment by noahpresler** [comment]
Even on bridged I am getting the error :( consistently and on the 'hopkins' network (not guest net)

**Comment by noahpresler** [comment]
I am on my home network and it worked...so I guess moral of the story is don't use hopkins wifi?
